### ISSUE TITLE
Custom page designs

### ISSUE THREAD

**Issue by j-ferber** [stevensblueprint/inreach-website#13]
**For Designer**

InReach sent us their Figma containing their common components here:
https://www.figma.com/file/gl8ppgnhpSq1Dr7Daohk55/Design-System-(2023)?type=design&node-id=234-8266&mode=design&t=7ksZDCQjFFH4NJ8y-0

Use these components to design the pages present on their current InReach site here:
https://inreach.org/

Some examples are but not limited to:
- Landing (home) page
- Mission page
- About us page
- Vetting process page
- Awards page
- Donate

**Comment by ShawnAviles** [comment]
Here is a link to current Blueprint Figma that you can use as a reference https://www.figma.com/file/1aCMwM49oVOpcJbQ72HaS2/Blueprint?type=design&node-id=2-9&mode=design
