### ISSUE TITLE
Two Column Markdown

### ISSUE THREAD

**Issue by j-ferber** [stevensblueprint/inreach-website#30]
For this issue, you will need to implement the Our Impact block from the our-impact page using TinaCMS.

Here is a reference to what the block currently looks like:

![image](https://github.com/stevensblueprint/inreach-website/assets/119906373/635c4a1b-b5b3-41bb-945e-06de445e8b82)

For an intro, you could look at the takeActions block or the example repo in the info doc.

**Comment by ShawnAviles** [comment]
# Scope Change

This issue will now be focused on creating a two column layout of rich text on both sides for a more common use case. It can be used to create this 'Our Impact' block once it is done.

![Image](https://github.com/user-attachments/assets/b20df48a-4170-40a6-83c1-49f094c3c36a)

**Comment by Lucasha11** [comment]
Story Points: 2

**Comment by ShawnAviles** [comment]
Closed with PR #70
