### ISSUE TITLE
Free Marketing Materials Block

### ISSUE THREAD

**Issue by j-ferber** [stevensblueprint/inreach-website#32]
For this issue, replicate the marketing materials gallery/collage that can be found on the marketing-materials page.

Here is a reference to the current design:

![image](https://github.com/stevensblueprint/inreach-website/assets/119906373/2bfcf7a6-7631-4270-8801-e98af0adcd12)

For an intro to TinaCMS, look at the current takeActions component or the example repository in the info doc.

**Comment by Lucasha11** [comment]
"Photo Gallery component"

Each image when clicked triggers a pop-up gallery

Story Points: 8
