### ISSUE TITLE
Prettier Hook for Formatting

### ISSUE THREAD

**Issue by j-ferber** [stevensblueprint/inreach-website#33]
For this issue, you will have to add a husky hook for pre-commit and pre-push. This will require you to install the package listed here: https://www.npmjs.com/package/husky

Here is a reference to a recent commit by Miguel doing the same: https://github.com/stevensblueprint/aad-admin/pull/152/files 

In our case, we only need npm run lint && npm run format

**Comment by brrryry** [comment]
Just added husky! As far as I know, the pre-commit commands run fine (.husky/pre-commit). I'll submit a PR now.
